name: Create Releases

on:
  schedule:
    # 1st of every month at 00:00 UTC
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set date as release tag
        id: run_date
        run: |
          echo "release_tag=$(date -u +%F)" >> $GITHUB_OUTPUT
          echo "release_date_nodash=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install html2markdown
        run: |
          go install github.com/JohannesKaufmann/html-to-markdown/v2/cli/html2markdown@latest
          $(go env GOPATH)/bin/html2markdown --version

      - name: Generate documentation
        run: |
          git clone --depth=1 https://github.com/typst/typst
          cd typst/docs
          cargo doc

      - name: Copy documentation to root
        run: |
          mkdir _html
          cp -r typst/target/doc/typst_docs/* _html/

      - name: Convert HTML to Markdown
        run: |
          mkdir -p _markdown

          find _html -type f -name "*.html" | while read html_file; do
            relative_path="${html_file#_html/}"
            md_file="_markdown/${relative_path%.html}.md"
            mkdir -p "$(dirname "$md_file")"
            $(go env GOPATH)/bin/html2markdown --input "$html_file" --output "$md_file"
          done

      - name: ZIP html
        run: |
          cd _html
          zip -r ../typst-docs-${{ steps.run_date.outputs.release_date_nodash }}-html.zip .
          
      - name: ZIP markdown
        run: |
          cd _markdown
          zip -r ../typst-docs-${{ steps.run_date.outputs.release_date_nodash }}-markdown.zip .

      - name: Generate SHA256 checksums
        run: |
          for file in *.zip; do
            if [ -f "$file" ]; then
              sha256sum "$file" > "$file.sha256";
            fi
          done

      - name: Create GitHub Release and upload files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.run_date.outputs.release_date_nodash }}
          name: "${{ steps.run_date.outputs.release_date_nodash }}"
          files: |
            *.zip
